In [1]:
import pandas as pd
import numpy as np

In [2]:
train = pd.read_csv("../input/train.csv")

In [3]:
train.head(20)

    ImageId_ClassId                                      EncodedPixels
0   0002cc93b.jpg_1  29102 12 29346 24 29602 24 29858 24 30114 24 3...
1   0002cc93b.jpg_2                                                NaN
2   0002cc93b.jpg_3                                                NaN
3   0002cc93b.jpg_4                                                NaN
4   00031f466.jpg_1                                                NaN
5   00031f466.jpg_2                                                NaN
6   00031f466.jpg_3                                                NaN
7   00031f466.jpg_4                                                NaN
8   000418bfc.jpg_1                                                NaN
9   000418bfc.jpg_2                                                NaN
10  000418bfc.jpg_3                                                NaN
11  000418bfc.jpg_4                                                NaN
12  000789191.jpg_1                                                NaN
13  000789191.jpg_2                                                NaN
14  000789191.jpg_3                                                NaN
15  000789191.jpg_4                                                NaN
16  0007a71bf.jpg_1                                                NaN
17  0007a71bf.jpg_2                                                NaN
18  0007a71bf.jpg_3  18661 28 18863 82 19091 110 19347 110 19603 11...
19  0007a71bf.jpg_4                                                NaN